
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Production note:
//
// This project IS in production.
// At this stage we intentionally avoid Prisma migrations and use
// `prisma db push` as the schema sync mechanism.
//
// Rationale:
// - Neon + connection pooling
// - Single production database
// - Early-stage schema evolution
//
// Migration workflow may be introduced later once schema stabilizes.
export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
